general {
    col.active_border = rgba(cba6f7ee) rgba(f5c2e7ee) 45deg
    col.inactive_border = rgba(89b4faee)
}

decoration {
    shadow {
    	color = rgba(cba6f7ee)
    	color_inactive = rgba(89b4faee)
    }
}
