general {
    col.active_border = rgba(d3869bee) rgba(fabd2fee) 45deg
    col.inactive_border = rgba(8ec07cee)
}

decoration {
    shadow {
    	color = rgba(d3869bee)
    	color_inactive = rgba(8ec07cee)
    }
}
