general {
    col.active_border = rgba(a7c080ee) rgba(7fbbb3ee) 45deg
    col.inactive_border = rgba(83c092ee)
}

decoration {
    shadow {
    	color = rgba(a7c080ee)
    	color_inactive = rgba(83c092ee)
    }
}
