general {
    col.active_border = rgba(bb9af7ee) rgba(f7768eee) 45deg
    col.inactive_border = rgba(7dcfffee)
}

decoration {
    shadow {
    	color = rgba(bb9af7ee)
    	color_inactive = rgba(7dcfffee)
    }
}
