general {
    col.active_border = rgba(81a1c1ee) rgba(5e81acee) 45deg
    col.inactive_border = rgba(88c0d0ee)
}

decoration {
    shadow {
    	color = rgba(81a1c1ee)
    	color_inactive = rgba(88c0d0ee)
    }
}
