general {
    col.active_border = rgba(varac0ee) rgba(varac2ee) 45deg
    col.inactive_border = rgba(varac1ee)
}

decoration {
    shadow {
    	color = rgba(varac0ee)
    	color_inactive = rgba(varac1ee)
    }
}
